name: Pack Release

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Create output folder
        run: |
          mkdir dist

      - name: Zip datapack
        run: |
          cd catalog-dp
          cp ../short_readme.md README.md
          cp ../LICENSE LICENSE
          zip -r ../dist/catalog-dp-${GITHUB_REF_NAME}.zip .
          cd ..

      - name: Zip resourcepack
        run: |
          cd catalog-rp
          cp ../short_readme.md README.md
          cp ../LICENSE LICENSE
          zip -r ../dist/catalog-rp-${GITHUB_REF_NAME}.zip .
          cd ..

      - name: Zip mcdoc
        run: |
          cd types
          zip -r ../dist/catalog-mcdoc.zip .
          cd ..

      - name: Upload release assets
        uses: softprops/action-gh-release@v3
        with:
          files: ./dist/*.zip

      - name: Send Discord notification
        if: always()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: '[${{ github.event.repository.name }}] automated release'
          embed-url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          embed-description: |
            **Tag**: ${{ github.ref_name }}
            **Status**: ${{ job.status }}
          embed-timestamp: ${{ github.event.release.published_at }}
          embed-color: 0x66ee66
